version: '3.8'

services:
  app:
    build: .
    container_name: weathersplash
    restart: unless-stopped
    environment:
      - API_KEY=630982626f28e0d904622681501a58be
      - PORT=5000
    ports:
      - 5000:5000
    networks:
      - shared-network

networks:
  shared-network:
