version: '3.8'

services:
  app:
    build: .
    container_name: weathersplash
    restart: unless-stopped
    environment:
      - API_KEY=
      - PORT=8080
      - NODE_ENV=production
    ports:
      - 8080:8080
