version: '3.8'

services:
  app:
    build: .
    container_name: weathersplash
    restart: unless-stopped
    environment:
      - API_KEY=
      - PORT=5000
      - NODE_ENV=production
    ports:
      - 5000:5000
